webapp/app/js/models/repository.js, webapp/app/js/services/treestatus.js
``comm-central`` is for thunderbird and the name doesn't match between us and treestatus, so this is a fix for it.  We already had 1/2 the workaround in there to get the right url for ``treestatus`` based on our repo name for ``comm-central``.  This just goes the other direction in translating back to our repo name of ``comm-central`` from ``comm-central-thunderbird``
=> Bug 1088970 - fix treestatus for comm-central

webapp/app/js/models/repository.js
this check prevents checking the treestatus on the previous repo when switching.
=> Bug 1116804 - speed up repo switching by fixing error

webapp/app/css/treeherder.css, webapp/app/js/directives/clonejobs.js
Switched from using jQuery for showing/hiding and finding
classes to using DOM calls.  This ended up being about 17% faster when
toggling unclassified failures.
**Update**
With some suggestions from Mauro and the use of ``.classList.add()`` this is now benchmarking at 30% faster to show/add a job.
=> Bug 1110552 - faster ``showHideJob`` perf

webapp/app/css/logviewer.css, webapp/app/logviewer.html, webapp/app/partials/logviewer/lvLogSteps.html
I) 	In the first table, content is clipped and is patched by breaking words into new line .
II)	Link in the 1st table is removed and is replaced by plain text, with an additional 'link' representing href tag, This is added because, breaking a link won't be a good habit
III)  	In the 2nd table, clipping of content is patched by wrapping whitespace with changing 'whitespace' CSS property from whitespace='no-wrap' to whitespace='normal'
=> Bug 1060058 - clipping of logviewer UI in smaller browsers is patched 

webapp/app/css/treeherder.css, webapp/app/partials/main/thPinboardPanel.html
This work fixes Bugzilla bug [1074939](https://bugzilla.mozilla.org/show_bug.cgi?id=1074939).
This switches the conditional Save UI in the pinboard to be persistent. We enable the buttons when either:
* a job is pinned
* a classification comment is added (and therefore a job is pinned)
* a related bug is added (and therefore a job is pinned)
The Save UI cluster is unchanged in dimensions and location.
I removed the border from the parent div. There is now only margin. That div carries the title tooltip if the pinboard is empty, because in that scenario, the spans below it are disabled and so are incapable of displaying an alternate title.
The removal of that border also ensures 'No pinned jobs' only appears when the mouse actuallly enters the Save UI, rather than just near it.
Here's the …
=> Bug 1074939 - Switch to a persistent pinboard Save UI

webapp/app/css/treeherder.css
This tweak fixes Bugzilla bug [1118929](https://bugzilla.mozilla.org/show_bug.cgi?id=1118929).
Nothing exciting, but this removes the extra tab decoration in the active job panel tab. We already differentiate by color and luminance, and the perception of the active tab seems fine without it. 
There is some other bootstrap or treeherder active dotted border triggered on Firefox (for all the UI), but I haven't yet gotten to looking at that yet. So I've preserved the `outline: 0` override so we don't get that dotted outline on the tabs. Otherwise I would have removed the entire block of css.
Adding @maurodoglio for visibility in case I've missed some other reason why this white decoration was present. I've checked also and it doesn't appear used anywhere else.
Here's the …
=> Bug 1118929 - Remove job tab outline decoration

webapp/app/plugins/pinboard.js
This work fixes Bugzilla bug [1118345](https://bugzilla.mozilla.org/show_bug.cgi?id=1118345).
If the user hasn't entered any bug number in the add related bug field, we now ignore it instead of creating an empty bug association on *enter*.
So the scenario in question we'd have:
Pre fix we'd have:
Post-fix we now have:
I've tested on both Firefox and Chrome, single and multiple resultsets, both using the 'r' key shortcut with rapid input, and the manual [+] icon, and in conjunction with the other pinboard shortcuts (pin, save, clear, comment). Everything seems to be working fine.
Tested on Windows:
FF Release **34.0**
Chrome Latest Release **39.0.2171.95 m**
Adding @camd for review and @rvandermeulen for visibility.
=> Bug 1118345 - Ignore empty related bug input fields on entry

webapp/app/plugins/pluginpanel.html
This tweak fixes Bugzilla bug [1119038](https://bugzilla.mozilla.org/show_bug.cgi?id=1119038).
This updates the logviewer icon for jobs whose status is either failed, pending or unavailable. So they also receive the new icon, rather than the old glyph.
For some reason I hadn't hit any jobs in progress during testing of [bug 1057349](https://bugzilla.mozilla.org/show_bug.cgi?id=1057349) until it was pushed to stage.
Here's the fix:
Tested on Windows:
FF Release **34.0**
Chrome Latest Release **39.0.2171.95 m**
Adding @camd for review.
=> Bug 1119038 -  Update the logviewer icon for pending/failed jobs

webapp/app/js/values.js
We haven't run jobs on 10.9 for over a month since we decided to leapfrog that platform and move directly to 10.10. The 10.9 jobs when they were running were only on cedar.
=> Bug 1119412 - treeherder should display results for 10.10 test jobs

webapp/app/help.html, webapp/app/index.html, webapp/app/js/directives/resultsets.js, webapp/app/logviewer.html, webapp/app/partials/logviewer/lvLogSteps.html, webapp/app/partials/main/jobs.html
It's currently (a) incorrectly being used for internal navigation links,
and (b) being used in cases where the user would likely not expect it.
eg: the standalone help page, where having to use the back button would
not lose any state (unlike the main Treeherder UI).
=> Bug 1077554 - Use target="_blank" in fewer places

webapp/app/plugins/failure_summary/controller.js, webapp/app/plugins/failure_summary/main.html
* Removes the temporary workaround added by https://bugzilla.mozilla.org/show_bug.cgi?id=1059949.
* Renames `{open_recent,all_others}_hidden` to `valid_{open_recent,all_others}` and inverts the conditionals accordingly.
* Adds the missing `(... || !suggestion.valid_open_recent)` to the all_others ng-if, which was the cause of this bug.
* Also adjusts the behaviour when open_recent exceeds the max bug count, such that we now no longer show the bugs from all_others, since they are likely also not relevant. ie we now show the "Exceeded max bug suggestions" error in more cases.
* Renamed `suggestion.open_others` to `suggestion.clicked_show_more` since it was too confusing alongside "all_others" and "open_recent".
=> Bug 1107987 - Correctly show bug suggestions from the all_others bucket

dist/index.html, dist/logviewer.html, webapp/app/index.html, webapp/app/logviewer.html
Now that we default to the same host for the service, we don’t need a
local.conf.js file to work properly.  Removing this prevents the
accident of stage pointing to prod or vice-versa, etc.
=> bug 1071541 - remove local.conf.js from the grunt build

webapp/app/plugins/talos/main.html
This will work once these are fixed: https://github.com/bgirard/cleopatra/pull/54 , https://bugzilla.mozilla.org/show_bug.cgi?id=1121571 , https://bugzilla.mozilla.org/show_bug.cgi?id=1122848
Here's the motivation, copied from https://bugzilla.mozilla.org/show_bug.cgi?id=1122848#c0 :
I'd like to make Talos profiles accessible in cleopatra (our profile visualization / consumption tool) through a simple link on treeherder.
When you push to try with "mozharness: --spsProfile" at the end of the try chooser commit message, Talos will run its performance tests under a profiler, create zip files that contain the collected profiles, and put them in the MOZ_UPLOAD_DIR. These files can then be downloaded using the "artifact uploaded" links on treeherder. At the moment, the user then has to unzip …
=> When selecting a Talos run, for each uploaded profile zip, show a link for opening it directly in Cleopatra.

webapp/app/css/treeherder.css, webapp/app/help.html, webapp/app/js/directives/main.js, webapp/app/plugins/controller.js, webapp/app/plugins/pluginpanel.html
This work fixes Bugzilla bug [1120133](https://bugzilla.mozilla.org/show_bug.cgi?id=1120133).
This allows the user to hover over the logviewer or raw log icon, which injects into a placeholder clipboard div a specified value. This can then be directly copied to the users' system clipboard.
In the change below, we mimic the Trello solution in angular. Here's the general workflow scenario:
* User hovers over a log icon
...![mouseenterhover2](https://cloud.githubusercontent.com/assets/3660661/5824347/066a5394-a0b2-11e4-880d-638da21d840d.jpg)
* User simply issues a copy to their clipboard via **ctrl+c** or **cmd+c**
* User pastes it somewhere, for example in channel
...![linkpaste](https://cloud.githubusercontent.com/assets/3660661/5824215/0311b9cc-a0b1-11e4-84ff-892ecba930f5.jpg)
So the …
=> Bug 1120133 - Enhance copy of logviewer/raw log icon links

webapp/app/index.html, webapp/app/js/directives/clonejobs.js, webapp/app/partials/main/jobs.html
say “>20” on the revision button
say “… and more” in the revision list instead of “… and X more”
This is the companion to https://github.com/mozilla/treeherder-service/pull/318.  Best to merge them both prior to pushing.
=> Bug 1119028 - remove exact count of revisions

webapp/app/plugins/controller.js
Supplemental fix to Bugzilla bug [1120133](https://bugzilla.mozilla.org/show_bug.cgi?id=1120133).
This removes the `/ui` path fragment from the logviewer icon 'hover' url, as it is not needed on production.
Someone with vagrant will want to sanity-check this change locally before merge. I have checked the existing production environment works without the fragment, so it should work.
Not locally tested, per above.
Adding @camd for review and a local check.
=> Bug 1120133 - Remove ui fragment from logviewer hover link

webapp/app/css/treeherder.css, webapp/app/partials/main/jobs.html
This work fixes Bugzilla bug [1118253](https://bugzilla.mozilla.org/show_bug.cgi?id=1118253).
In it, we close the selected job when clicking in the get-next footer, and also provide a reasonably sized click region below it for the same functionality for short result sets.
Here's the get-next behavior pre-click and post-click (clicking in the grey region):
And the behavior in the region below the job rows, pre-click and post-click:
For now we just use a 300px static spacer, and don't attempt to calculate a dynamic one, given the vagaries of the movable job panel, pinboard, and pin-board job panel combo (open or closed), all of which affect a potential dimension calculation. We could revisit that later if needed.
Tested on Windows:
Chrome Latest Release **40.0.2214.93 …
=> Bug 1118253 - Clear job selection in page bottom and get-next-footer

webapp/app/plugins/failure_summary/main.html
This:
* Removes unnecessary resolution check for open_recent bugs (since the bugs by definition are always open).
* If a bug is resolved/closed, shows the resolution (eg 'FIXED', 'INVALID') in the tooltip for the bug link. With this change, there would have been three places that were conditional on |bug.resolution != ''| so I've switched to an ng-if and two versions of the link.
=> Bug 1124792 - Failure summary: Add bug resolution to closed bug tooltips

webapp/app/css/treeherder.css, webapp/app/partials/main/jobs.html
This is a continuation of work for Bugzilla bug [1118253](https://bugzilla.mozilla.org/show_bug.cgi?id=1118253).
With sheriff feedback, we decided to try for another approach to clearing the selected job in the area below the get-next footer. Preference is for trying to do it without a spacer, and try for my previously investigated approach to see if we can handle all the events correctly in `th-content` and clear it there.
I made sure the removal is working properly and we are back to our old state, and it seems to be fine.
Tested on Windows:
Chrome Latest Release **40.0.2214.93 m**
Adding @wlach for review and @edmorley and @rvandermeulen for visibility.
=> Bug 1118253 - Remove footer spacer for a future clearing method

webapp/app/css/treeherder.css
This work fixes Bugzilla bug [1124266](https://bugzilla.mozilla.org/show_bug.cgi?id=1124266).
In it, we allow the user a resizable job details panel, up to 75 percent of the content height. For the last half year or so, it had been fixed at 35 percent and not adjustable. While there, I also made the two dynamic content containers in the pinboard (pinboard content, related bugs) adjust on the fly to the user's panel size.
Here's the pinboard specifically, before and after. Some minor tweaks, generally the same but slight optimization in height for more content space:
Here is the proposed default launch size of the job panel (unchanged):
Here is the maximum size of 75 percent, which requires manual interaction:
And here is an example of a larger screen and content, in use at that size: …
=> Bug 1124266 - Allow a larger max size for job details panel

webapp/app/css/treeherder.css, webapp/app/index.html, webapp/app/js/controllers/main.js, webapp/app/js/directives/clonejobs.js, webapp/app/js/directives/resultsets.js, webapp/app/js/filters.js, webapp/app/js/providers.js, webapp/app/partials/main/jobs.html, webapp/app/partials/main/thActionButton.html, webapp/app/partials/main/thResultCounts.html, webapp/app/partials/main/thResultStatusCount.html, webapp/app/plugins/controller.js
This work fixes Bugzilla bug [1118253](https://bugzilla.mozilla.org/show_bug.cgi?id=1118253).
In it we support clearing a job, with a click anywhere in the resultset content area that isn't
* a link
* a resultset filter
* a resultset menu dropdown
* resultset button
* a job
* get-next 10 | 20 | 50 footer buttons
Otherwise, everywhere else on the main content area is fair game to clear the selected job, as one would expect it should be.
We basically place a clear on `th-content`, and then test the clicked element to see if it contains a `ignore-job-clear-on-click` attribute. If it doesn't have one, we clear the job.
Other than jobs, these areas highlighted, are the only areas *excluded* from clearing:
So we also fix Julien's workflow of clicking in the empty space below short pushes, …
=> Bug 1118253 - Deselect job when clicking any open area on main page

webapp/app/css/treeherder.css, webapp/app/js/controllers/jobs.js, webapp/app/js/controllers/main.js, webapp/app/js/directives/clonejobs.js, webapp/app/js/directives/persona.js, webapp/app/js/directives/resultsets.js, webapp/app/js/models/resultsets_store.js, webapp/app/js/providers.js, webapp/app/js/services/jobfilters.js, webapp/app/partials/main/jobs.html, webapp/app/partials/main/thActionButton.html, webapp/app/partials/main/thResultCounts.html, webapp/app/partials/main/thWatchedRepoNavPanel.html
**READY FOR MERGE**
This removes the status counts and replaces them with a % progress and count of "in progress" jobs like so:
Before:
After:
This also attempts to "remove clutter" from the resultset status bar.
Also fixed:
* global collapse button just collapses revisions, not everything.  remove drop-down.
* cleaned up resultset buttons and moved right.
* global filtering of coalesced (was not functioning)
* Fixed counts of pending vs. coalesced that was off
* removed counting code in ``clonejobs.js`` because ``resultset_store`` already does it
* made failed jobs have transparent background when classified
* removed dead code from clonejobs for showing only revisions without jobs.
=> Bug 1127454 - Remove status counts

webapp/app/index.html, webapp/app/js/directives/clonejobs.js
Two parts:
1) Rename comments_bug_link to escaped_comment_linkified - to make the relation with 'escaped_comment' clearer.
2) Only display first line of each commit message - to make the list of commit messages shown for each push less cluttered. In the future, bug 1061283 will change the API so that there are separate fields for the first line and full comment message strings, so at that point we'll switch to using those instead.
=> Bug 1073409 - Only display first line of each commit message

docs/installation.rst, webapp/app/js/config/sample.local.conf.js, webapp/config/karma.conf.js
* The sample config is optional, so don't use it for tests …
We want the sample config to now point at the production service API to make the first-run experience for new contributors easier. However the tests use the sample config as part of the test run, so this breaks them. However since the sample config is now optional, we can just not use it at all during the tests to fix the failures.
* Improve the API back-end prefs in the sample local config …
It's now easier to switch between the API back-ends and harder to make typos. The default backend has also been changed to production (instead of using the same host), since local.conf.js is now optional, so if someone just wants to use the same host as the UI for the back-end, then they can just not create local.conf.js in the first place. …
=> Improve the initial setup experience for new contributors to the UI

webapp/app/js/perf.js
* Hide tooltip when user hovers away from a datapoint (and it is isn't
locked)
* Use a grab cursor when hovering over a datapoint
=>  Bug 1132509 - Improve graph tooltip behaviour 

webapp/app/index.html, webapp/app/js/controllers/main.js, webapp/app/partials/main/thPinboardPanel.html, webapp/app/plugins/pinboard.js
This work fixes Bugzilla bugs [1121631](https://bugzilla.mozilla.org/show_bug.cgi?id=1121631) and [1118342](https://bugzilla.mozilla.org/show_bug.cgi?id=1118342).
This adds a few things beyond previously reverted PR https://github.com/mozilla/treeherder-ui/pull/338. Specifically it:
* addresses the slowdown in toggle unclassified
* uses `$scope.$evalAsync` for better optimization where formerly `$digest` was used
* ignores shortcuts on manual entry of classification comments with the `allowKeys()` function
An article on.Async can be found [here](http://www.bennadel.com/blog/2605-scope-evalasync-vs-timeout-in-angularjs.htm).
I've also left in some placeholders for next/previous job navigation, for @dewgeek's upcoming PR. In the event mine lands first, they can just be un-commented (and …
=> Bug 1121631 - Implement moustrap shortcuts

webapp/app/plugins/similar_jobs/controller.js, webapp/app/plugins/similar_jobs/main.html
update_similar_jobs() now resets the list on changing the selected job
get_list() now appends the new data by merging the arrays (using jQuery; I didn't want to use .concat because it's not in-place)
=> Bug 1095100 - Let "Show previous jobs" append data instead of replacing it

webapp/app/plugins/pluginpanel.html
This fixes Bugzilla bug [1135743](https://bugzilla.mozilla.org/show_bug.cgi?id=1135743).
With the recent work to make less launching of new tabs, I think this title needed a little update. I mused about trying to wordsmith it further, but eventually decided just to remove the tab reference for now.
Everything seems fine with the change.
Tested on OSX:
Adding @edmorley for visibility and review.
=> Bug 1135743 - Update job details Filter job title

webapp/app/plugins/similar_jobs/controller.js, webapp/app/plugins/similar_jobs/main.html
Reset similar_job_selected to null so that the ng-if in the main.html discards the current detail pane and after the request finishes the detail pane gets added again with the new data.
If there's need to add a loading animation I can add that as well.
=> Bug 1134746 - Fix similar jobs selection

webapp/app/js/values.js
Add support for Graphene builds. I also bumped the "other" group to 99 because it seems like it should always be last. Let me know if I should use 42 though.
=> Add graphene build support.

webapp/app/css/treeherder.css
This fixes Bugzilla bug [1061304](https://bugzilla.mozilla.org/show_bug.cgi?id=1061304).
This changes the behavior at smaller browser widths (or more job control icons in the future), to clip/hide them, rather than flow them over the job results content. Here's the before and after:
We are applying this to the entire bottom navbar, as the right hand side also receives this class. There seem no ill effects from that on either browser, and presumably if we populated the bottom right side of the navbar with similar icons, we'd want that behavior anyway.
@wlach if you could give this a quick interactive test also, that would be awesome :)
=> Bug 1061304 - Clip instead of flow job control icons

webapp/app/js/controllers/main.js
Supplemental to @dewgeek 's work in bug [1089737](https://bugzilla.mozilla.org/show_bug.cgi?id=1089737) nothing major, but this part of my comment was intended for removal before landing, so it looks the same as all the other shortcut comments.
Adding @camd for review.
Tested on OSX:
=> Bug 1089737 - Tweak next/prev shortcut comment

webapp/app/help.html
This fixes Bugzilla bug [1126525](https://bugzilla.mozilla.org/show_bug.cgi?id=1126525).
This links the Spidermonkey and Hazard descriptors in the Help, to their respective wikis. Here's the after:
I chose not to link the single line "Spidermonkey Hazard" separately as "Spidermonkey" and "Hazard", for clarity. Since it seems to be a Hazard build, and there are lots of Spidermonkey links present.
If its well received we can consider doing it with other jobs not specified, if they have similar wikis available.
Adding @edmorley for review and feedback.
=> Bug 1126525 - Link sm/hazard Help job descriptions to wikis

webapp/app/js/controllers/main.js, webapp/app/partials/main/thPinboardPanel.html
This work fixes the second half of Bugzilla bug [1118342](https://bugzilla.mozilla.org/show_bug.cgi?id=1118342).
In it, we support the shortcut **ctrl+enter** to save a classification while focused in the related bug input field (in addition to the comments field, whose functionality already exists).
To do a basic workflow:
* pin a job
* **'r'** or click on the [+] icon to open the related bugs input
* type or paste a number
* **'ctrl+enter'** to save the classification
Expected:
The classification should be saved, and the input field closed and rendered as a new bug.
Everything seems in order, I've tried as many workflows I can think of, switching contexts trying to 'c' to add a comment (we will interpret that as a regular character and validate the input as a number via the markup), …
=> Bug 1118342 - Support ctrl+enter save when focused in add-related-bug

webapp/app/css/treeherder.css, webapp/app/plugins/pluginpanel.html, webapp/app/plugins/talos/main.html
This patch gets rid of overflowing for the bottom header and propagates down the content heights in a way, that the plugins can have proper scroll panes.
If we wouldn't explicitly inherit the height, it'd get calculated by its children, and therefore the scroll pane would overflow.
The change to pluginpanel.html is needed because otherwise we would have multiple div's with an explicitly set height, although their contents are display:none.
=> Bug 1094466 - Separate scroll-panels for similar jobs panel

webapp/app/css/treeherder.css, webapp/app/help.html, webapp/app/js/controllers/filters.js, webapp/app/js/controllers/main.js, webapp/app/js/directives/main.js, webapp/app/partials/main/thWatchedRepoNavPanel.html
This work fixes Bugzilla bug [1133545](https://bugzilla.mozilla.org/show_bug.cgi?id=1133545).
This adds the **f** key as a shortcut to focus the "Filter platforms & jobs" field. In it we:
* similarly issue a click in the shortcut rather than focus, which selects the string if it exists
* create a new `clickThis` directive to support that behavior
* no longer re-invoke the filter as soon as the cell is empty, instead only after the user hits Enter
* create a global behavior which suppresses (makes transparent) *all* placeholder text on focus
The suppression/transparency of placeholder text on click was approved by Ryan in channel. I checked and it didn't seem to have any adverse impacts in the pinboard, etc. It seems to add clarity, but we could easily remove it if needed.
Invoking an …
=> Bug 1133545 - Create a shortcut to focus the Filter field

webapp/app/css/treeherder.css, webapp/app/help.html
This work fixes Bugzilla bug [1139565](https://bugzilla.mozilla.org/show_bug.cgi?id=1139565).
In it we improve and make a more direct association with what the users see in Help, with what they see in the platform. Here's the before:
And proposed:
I used a style evocative of the running state/color, but slightly less dark, so the columns don't compete so much with their adjacent text. But so they are still readable. I'd be interested to know how that luminance looks on other folks machines to make sure it's ok.
Adding @wlach for review and @edmorley for visibility.
=> Bug 1139565 - Add more polish to the Help build/job tables

webapp/app/js/controllers/main.js
This is a supplemental fix to Bugzilla bug [1089737](https://bugzilla.mozilla.org/show_bug.cgi?id=1089737).
This unbinds the left/right keys when in any mousetrap enabled input, for example add-related-bugs or classification-comment. Without the unbind, if the user uses the left or right arrows to traverse text in those inputs, the selected job changes.
Here's an example screen grab of that workflow:
I did some tidying while I was there, and a planned annotation of the unbound keys now that we have exceeded the styleguide max line length.
Everything seems to be working fine in both browsers.
=> Bug 1089737 - Unbind left/right navigation in mousetrap inputs

webapp/app/js/controllers/jobs.js, webapp/app/js/values.js, webapp/app/plugins/controller.js, webapp/app/plugins/similar_jobs/main.html
This fixes Bugzilla bug [1139301](https://bugzilla.mozilla.org/show_bug.cgi?id=1139301).
This switches the date format for the job details panel for Request, Start, and End, from **m/d/yy**, to the format highlighted below.
In addition to removing ambiguity for all users (folks who read **m/d** or **d/m**), it makes it consistent with the resultset header. We use 24hour time, but we could add an AM/PM here if we feel it is really needed.
I'm awaiting feedback from @darktrojan just to make sure he's happy with it, before we merge.
Adding @edmorley for review and @darktrojan for visibility.
=> Bug 1139301 - Make the date-format consistent and centralized

webapp/app/partials/main/thWatchedRepoNavPanel.html
This fixes Bugzilla bug [1140054](https://bugzilla.mozilla.org/show_bug.cgi?id=1140054).
Nothing exciting, just updating the Show/hide tooltip so it is consistent with the terminology used elsewhere on the platform for exclusion.
=> Bug 1140054 - Update Show/hide hidden jobs tooltip to exclusion

webapp/app/help.html
This is a supplemental fix for Bugzilla bug [1089737](https://bugzilla.mozilla.org/show_bug.cgi?id=1089737).
Nothing major, we just needed to update to reflect @dewgeek's recent change for prev/next job navigation. Here's the Help update:
Some other minor tweaks were made in ordering and for pin-click, while I was there.
=> Bug 1089737 - Update Help shortcuts for left/right navigation

webapp/app/js/perf.js
This is supplemental to fixed bug [1139301](https://bugzilla.mozilla.org/show_bug.cgi?id=1139301).
Nothing exciting, just making the perf date format consistent with the rest of treeherder.
Not knowing how else the date  might be reused in perf I chose not to use an angular date filter; additionally, injecting a `thDateFormat` into perf appears problematic because you can't easily have two ng-apps (treeherder, perf) live and be accessed from the same values.js file. So unless ng-app=perf becomes ng-app=treeherder, it's a moot point. I chatted with @camd and he agreed.
Here's the current date style:
And proposed (same as elsewhere in Treeherder):
I'm easy though. If there's compelling UX reasons for keeping the date format as-is for perf, that makes total sense to me. …
=> Bug 1139301 - Update perfherder date format

Gruntfile.js
All of the other js files are given filenames containing their hashes, during the grunt build, in order to prevent over-caching. This makes us do the same for perf.min.js too.
=> Bug 1141533 - Enable cache busting for perf.min.js

webapp/app/js/controllers/main.js
This tweak fixes Bugzilla bug [1137927](https://bugzilla.mozilla.org/show_bug.cgi?id=1137927).
In it, the the job panel will persist if the user clicks in an empty main page area, if there are jobs pinned.
The **esc** shortcut and the [x] close icon will continue to work as normal, closing the job panel whether or not jobs are pinned.
There are no visible changes, but here's a screen grab of the scenario:
It's an interesting UX change, I think we want to expose users to it on dev, before pushing it to stage/prod. Without prior knowledge of the change in behavior, it may feel a bit strange for users.
Chrome Latest Release **41.0.2272.76** (64-bit)
Adding @wlach for review and @edmorley for visibility.
=> Bug 1137927 - Persist job details panel when jobs are pinned

webapp/app/js/controllers/jobs.js, webapp/app/js/controllers/logviewer.js, webapp/app/plugins/controller.js, webapp/app/plugins/similar_jobs/controller.js
When the Service is generating the structured log summary artifact, the
UI needs to handle that it will come back in the
endpoint for log artifacts. This change will just ignore the new
artifact.
=> Bug 1113873 - Support existence of struct log summary artifact

webapp/app/css/logviewer.css
This work fixes Bugzilla bug [1140734](https://bugzilla.mozilla.org/show_bug.cgi?id=1140734).
In it we convert the log lines to fixed-width, and hopefully add some subtle readability improvements. Here's the before:
And I went with a slightly stronger red to help the errors pop a bit better than they did before:
I also reduced the log line text size to small. I am hopeful that is still readable on all systems, since it gives us more content per page.
I have some other enhancement ideas, but we can leave those for later.
I had to make a css addition to the load help message "Click a log step above to view", so it remains sans serif. During the color change for errors I removed a css reference to `lv-line-number` since we aren't currently drawing them and that class …
=> Bug 1140734 - Add more polish to logviewer log lines

webapp/app/js/models/repository.js
Some users set dom.storage.enabled to false to disable local storage for privacy reasons. Let's handle this more gracefully. In the future when we use local storage for more features, we'll want to break this out to somewhere common and use a shim of some sorts, but for now this will do.
=> Bug 1136232 - More gracefully handle disabled sessionStorage

webapp/app/partials/main/jobs.html
The second argument to fetchResultSets() determines whether the current result set filters are preserved for the call to fetch more result sets. Previously the filters were not preserved, causing unwanted result sets to be returned (eg pushes by other authors, when the author filter was being used).
=> Bug 1134840 - Use the current result set filters when using "get next"

webapp/app/css/treeherder.css, webapp/app/partials/main/thPinboardPanel.html
This work fixes Bugzilla bug [1137456](https://bugzilla.mozilla.org/show_bug.cgi?id=1137456).
This consolidates the clear-all button as a drop down inside the existing menu. While there I de-cluttered and removed the `fa` icons, and also added in a check so we also expose the drop down menu if there is just a related-bug. This allows them to clear-all via the UI, like they would via the shortcut.
Here's the after (empty pinboard, and populated):
Everything seems to be working fine on Firefox and Chrome.
If we wanted later we could add a `hasComment()` pinboard service api or similar, and use that check also to enable the dropdown if the user types a comment into an otherwise empty pinboard panel. Perhaps we could also disable/dim the 'Save * only' menu entries if no …
=> Bug 1137456 - Consolidate the pinboard save/clear-all cluster

webapp/app/plugins/controller.js
Since otherwise we accidentally exclude logs other submitters (eg TaskCluster), since they all have arbitrary names.
=> Bug 1142559 - Exclude json logs using a blacklist rather than whitelist

webapp/app/css/treeherder.css
This tweak fixes Bugzilla bug [1142244](https://bugzilla.mozilla.org/show_bug.cgi?id=1142244).
This improves the readability of the cancelled job color for @AutomatedTester, and more closely matches that of TBPL. Initially we had implemented a paler pink to de-emphasize cancelled jobs. Sheriffs are fine with this change.
We start with TBPL's `#f0c` and reduce the saturation to 75% to match the same sat of blue/green jobs. So we end up at at pink of `#ff40d9`. And for the corresponding roughly 50% saturation field set color, we end up at `#ff80e5`.
Here is the before:
And here is proposed:
If it's too vibrant we can always tone it down a little, if needed.
Chrome Latest Release **41.0.2272.76** (64-bit)
Adding @wlach for review and @edmorley for …
=> Bug 1142244 - Improve readability of cancelled job colors

webapp/app/plugins/pluginpanel.html, webapp/app/plugins/similar_jobs/main.html
This tweak fixes Bugzilla bug [1142994](https://bugzilla.mozilla.org/show_bug.cgi?id=1142994)
Just some LHF, I had been staring at this awhile and thought I would try to declutter, consolidate terminology, and try to order Similar Jobs consistently with the Job Status pane.
Basically we remove "Time" in the job details since the adjacent value is implicitly Time. We match case of "Job Name" to "Job name" in Similar Jobs, specify the "Option" as a Build option". We also switch "Push timestamp" to Pushed, and we reorder accordingly in Similar Jobs to match the sequence in Job Status.
Here is the after:
I am not sure if "Build option" is always a build option, or if it can be something else. In which case I will update that just to say "Option" (assuming it is always …
=> Bug 1142994 - Consolidate terms and order in Job details panel

webapp/app/js/directives/clonejobs.js
This tweak fixes Bugzilla bug [1143092](https://bugzilla.mozilla.org/show_bug.cgi?id=1143092).
This makes the job button duration value on a completed job, consistent with the job details pane, and the similar jobs pane. The job button is now start-end, not requested-end, which makes all three match.
Here's the after (change in the tooltip):
Everything seems fine on a variety of jobs, in several different repos, on both browsers tested.
I did a bit of linting while I was there.
Chrome Latest Release **41.0.2272.89** (64-bit)
Adding @lightsofapollo for review.
=> Bug 1143092 - Make job-btn duration start-end, not requested-end

webapp/app/css/logviewer.css, webapp/app/logviewer.html
This change is supplemental to broader work requested in Bugzilla bug [1102851](https://bugzilla.mozilla.org/show_bug.cgi?id=1102851).
Nothing major here, but for some reason, I think accidental, we unlinked the logviewer run-data revision SHA in this commit https://github.com/mozilla/treeherder-ui/commit/c7d10090a01e13f11438fd60ffe3b470e4f7a15d . I wanted to re-link it. While I was there I reduced the font sizes in the upper data blocks. It makes more real estate for the log lines below, and reduces the frequency of vertical overflow in the first data block.
Here's the before and after:
It seems to still be readable in testing on a lower res Windows machine and on my retina mbp.
There are other issues to be sorted (among many) but this addresses some small annoyances and will dovetail …
=> Bug 1102851 - Relinkify logviewer revision and reduce run-data font

webapp/app/help.html, webapp/app/js/controllers/main.js, webapp/app/js/providers.js, webapp/app/plugins/controller.js
This fixes Bugzilla bug [1143666](https://bugzilla.mozilla.org/show_bug.cgi?id=1143666).
This adds the '**r**' shortcut for retriggering a selected job. It also re-maps the add-related-bugs shortcut, which was '**r**', to '**b**'.
Everything seems to be working ok locally, but for a variety of unrelated reasons (local vagrant issue, LDAP access) I can't actually issue a retrigger. I just used a console print to make sure the shortcut was getting there with no lag, and it also correctly gave me the log-in warning balloon if I wasn't logged in.
The add-related-bugs shortcut seems to continue to work fine using its new '**b**', and integration testing with other pinboard shortcuts and next/prev job navigation, seems fine.
If you can try my branch and actually retrigger a job or two with your …
=> Bug 1143666 - Add a shortcut for retrigger job

webapp/app/css/treeherder.css, webapp/app/help.html
This update fixes Bugzilla bug [1144748](https://bugzilla.mozilla.org/show_bug.cgi?id=1144748).
In it we improve the readability of the shortcuts in Help. I just created a non-specific `kbd` class which we could use anywhere, but referenced its current use in treeherder.css.
Everything seems fine on both browsers.
Chrome Latest Release **41.0.2272.89** (64-bit)
Adding @edmorley for review.
=> Bug 1144748 - Improve readability of help shortcuts with keyboard icons

webapp/app/js/filters.js
This work fixes Bugzilla bug [1133021](https://bugzilla.mozilla.org/show_bug.cgi?id=1133021).
This linkifies all bugs and pull requests in a given commit message that match the following prefixes:
* "Bug ", "bug ", "-- "
* "PR#" "pr#"
Here's the before with an example test case (note also the commit-title populating the bug/pr links):
I've tested a variety of different messages (no bugs, single bugs/prs, multiple bugs/prs, identical bugs/prs, identically-prefixed bugs/prs, the originally reported bug revision ) and everything seems to be ok.
I tried a bunch of different implementations: loops, a function with passed params, doing the replace in one shot (problematic with "-- " and the $n param in the url vars), specifying the .replace string as a …
=> Bug 1133021 - Linkify all bugs and prs in revision commit messages

webapp/app/partials/main/thGlobalTopNavPanel.html, webapp/app/partials/main/thInfraMenu.html
Suggestions welcome for additions/removals/re-ordering of links.
@tojonmz I'm sure you'll have some styling ideas for this - I don't know whether it's best to land as is - and then let you do your (awesome) thing - or iterate here? I don't mind either way - though with the PTO might be hard to get this landed before TBPL end of life if we aim for styling perfection here :-)
=> Bug 1082771 - Add a static "Infrastructure" menu that links to existing dashboards

webapp/app/partials/main/thInfraMenu.html
I managed to accidentally remove these from the original PR before landing.
=> Bug 1082771 - Add headings/separators to the infra menu

webapp/app/css/treeherder.css, webapp/app/partials/main/jobs.html
This tweak hopefully addresses the bulk of Bugzilla bug [1112652](https://bugzilla.mozilla.org/show_bug.cgi?id=1112652), or enough we address the use problem of discoverability of a sharable url, for a single resultset.
I went through a variety of other wordings, some which I've included in case folks like anything better:
* "View only this resultset and url"
* "View only this resultset url"
* "View this resultset url"
Feel free to let me know if prefer any of those, or propose others, and I'll adjust :)
Chrome Latest Release **41.0.2272.89** (64-bit)
Adding @wlach for review and @armenzg and @KWierso for visibility.
=> Bug 1112652 -  Communicate the resultset date link is a permalink/url

webapp/app/css/treeherder.css
This fixes Bugzilla bug [1146970](https://bugzilla.mozilla.org/show_bug.cgi?id=1146970).
More LHF, I've been staring at this for months :) This removes the annoying blue space created by the `ul` when no failures or similar conditions exist, and no bugs are posted.
I took care to compensate for the change in all the other `li`s, and did a lot of blink testing to make sure the layout elements are identical to what they were before:
Everything seems fine and the other Annotation and Similar Jobs panels appear unaffected, as one would expect.
FF Release **36.0.4**
Chrome Latest Release **41.0.2272.104** (64-bit)
=> Bug 1146970 - Clean up bluespace in the Failure Summary

webapp/app/css/treeherder.css
World's shortest PR :), see Bugzilla bug [1147389](https://bugzilla.mozilla.org/show_bug.cgi?id=1147389) for details.
There wasn't really any other current work I could logically tie this to, so opened it separately.
Everything seems fine on both FF and Chrome.
FF Release **36.0.4**
Chrome Latest Release **41.0.2272.104** (64-bit)
=> Bug 1147389 - Purge some redundant padding in Failure Summary css

webapp/app/css/treeherder.css, webapp/app/partials/main/persona_buttons.html, webapp/app/partials/main/thGlobalTopNavPanel.html, webapp/app/partials/main/thLogoutMenu.html
This work fixes Bugzilla bug [1131830](https://bugzilla.mozilla.org/show_bug.cgi?id=1131830).
Per the bug thread with @edmorley and @KWierso, we now prevent the user from accidentally logging themselves out when working quickly near the Logout button by creating a nested menu. While there I added a bit of polish to cue the user they are logged in with Persona and also not occupy so much space. The same information is available to the user as before.
This Persona icon approach will also work nicely with an adjacent 'sheriff on duty' icon (bug [1144589](https://bug1144589.bugzilla.mozilla.org/attachment.cgi?id=8582586)), if we fix that issue also.
Here's the current appearance (logged in):
Here's proposed (logged in):
And on hover:
And posted menu:
All the dropdown menus are a bit big, that …
=> Bug 1131830 - Prevent accidental logouts with a dropdown logout menu

webapp/app/js/controllers/jobs.js, webapp/app/js/directives/clonejobs.js, webapp/app/js/providers.js
This fixes Bugzilla bug [1146651](https://bugzilla.mozilla.org/show_bug.cgi?id=1146651)
This removes references to per-resultset filters and related code. `resultSetFilterChanged` appeared it could be retired also. `resultStatusFilters` is still used for global filters.
Everything seems fine running locally, adding and removing Global filters, adding and removing custom text filters via 'Filter Platforms & Jobs' on both browsers.
I also tweaked adjacent comments referencing local filters.
I briefly searched treeherder-service out of interest, I didn't see anything obvious there that corresponded or would need removal.
FF Release **36.0.4**
Chrome Latest Release **41.0.2272.104** (64-bit)
Adding @camd for review.
=> Bug 1146651 - Remove legacy per-resultset filter code

webapp/app/js/models/resultsets_store.js
Fixes [Bug 1149348](https://bugzilla.mozilla.org/show_bug.cgi?id=1149348)
This would improve the categorization of Tier-2 jobs by visually retaining their job groupings, but still distinguishing them as Tier-2:
=> Bug 1149348 - Maintain tier-2 job groupings

webapp/app/plugins/controller.js
This fixes Bugzilla bug [1150159](https://bugzilla.mozilla.org/show_bug.cgi?id=1150159)
This prevents us from going farther down the code path to thModelErrors(?) which produces a persistent error message, and instead we test for `user.loggedin` on retrigger. This addresses the UX issue raised on IRC, in which James logged in, but the dialogue annoyingly remained up even after he had logged in.
I figured we'd just present a normal non-sticky which will disappear in 5000ms. By the time the user has started the login process, it will be gone.
Here's the proposed (non sticky launched):
There is a whole lot of interesting stuff that went on in the past several month to handle LDAP/HTTP auth stuff which I don't profess to grok, but I've included it here for reference:
* [Bug …
=> Bug 1150159 - Make retrigger check for login w/non-sticky warning

webapp/app/js/controllers/filters.js, webapp/app/js/controllers/jobs.js, webapp/app/js/models/resultsets_store.js
This fixes Bugzilla bug [1149576](https://bugzilla.mozilla.org/show_bug.cgi?id=1149576).
This adjusts the max pin count message, so when the user hits the limit on a re-pin, we no longer tell them about how many we added or not. Example workflow:
* pin All
* manually un-pin 1 job
* pin All again
Here's the current appearance:
Here's the proposed:
I considered injecting thPinboard into the various job and filter controllers, but instead decided to pass the maxSize as a new param, and rename the old max size as the `spaceRemaining` param, since that is what it is, upstream.
I thought this might be more economical than more injection. Everything seems fine in the Resultset pin-all, and the Filter Panel pin-all workflows.
`getAllShownJobs` seems to be only used with `pinAllShownJobs` so I am …
=> Bug 1149576 -  Adjust the max-pin count error message for clarity

webapp/app/css/treeherder.css, webapp/app/help.html, webapp/app/js/models/resultsets_store.js
This fixes [Bug 1151023](https://bugzilla.mozilla.org/show_bug.cgi?id=1151023)
Add query string param to UI to skip loading jobs.  This makes it much faster when a user just wants to see the revisions in a large number of resultsets.
Help section update:
=> Bug 1151023 - Nojobs option

webapp/app/js/providers.js
This fixes [Bug 1087349](https://bugzilla.mozilla.org/show_bug.cgi?id=1087349)
In these cases, there was a space in the aggregate platformId that was generated.  Then when we went to find that with JQuery to see if we should replace or add a new one, the space caused it to never be found (spaces are invalid).  So we added the new platform row.  
This fix ensures there are never spaces in the aggregate ids we generate.
=> Bug 1087349 - fix platform duplication on guessed platform names

webapp/app/js/services/main.js
This tweak fixes Bugzilla bug [1150905](https://bugzilla.mozilla.org/show_bug.cgi?id=1150905).
This reduces the time that a non-sticky notification appears.
I tried 4000ms, 3500, 3000, 2000, and ultimately went with 4000. It seems to give enough time for a new user who doesn't immediately look at the message to still see it and read it, while helping reduce tiled messages for existing users particularly on retrigger.
No changes visually, but here's a screen grab of a non-sticky message for reference.
FF Release **36.0.4**
Chrome Latest Release **41.0.2272.104** (64-bit)
Adding @edmorley for review.
=> Bug 1150905 - Shorten onscreen time for non-sticky notifications

webapp/app/js/directives/clonejobs.js
The tooltips for completed jobs were missing a space between the job name and the job result. In addition, the "check job details panel for eta" string is unnecessary, particularly now people are used to not having the eta there.
=> Bug 1153807 - Fix whitespace in job tooltips & reduce clutter

webapp/app/js/directives/clonejobs.js, webapp/app/js/services/jobfilters.js, webapp/app/js/services/main.js, webapp/app/plugins/controller.js, webapp/app/plugins/pluginpanel.html
Please merge this service PR first: https://github.com/mozilla/treeherder-service/pull/447
This fixes:
* ``job`` field in the details panel for Task Cluster jobs will be accurate and not refer to last Buildbot job that was selected.
* You can filter the Task Cluster job just like you can with a Buildbot buildername.
* Adds the job ``signature`` field to the search string to make it more accurate (we were often getting many other jobs when clicking this link to filter on Buildbot jobs).
=> Fix ``job`` field value for Task Cluster jobs and allow filtering

webapp/app/css/treeherder.css
This work addresses Bugzilla bug [1149340](https://bugzilla.mozilla.org/show_bug.cgi?id=1149340).
This attempts to add continued polish to the Similar Jobs tables:
* put the job element in relief from its row selection
* a more subtle row and color selection
* remove pointer behavior over elements (Job, Date) which don't do anything
* make this panel plain white not off-white
* override bootstrap and present the content vertically centered in its row
Here's the current:
Here's the proposed:
I tried to be specific in the targeting so we don't mess up anything else. It would be good for folks to play with it on dev for a bit to be sure. I contemplated preserving the column borders but accidentally-on-purpose flipped them off in inspector and it seems quite elegant without them. The data …
=> Bug 1149340 - Improve readability of Similar Jobs tables

webapp/app/js/directives/clonejobs.js, webapp/app/plugins/pluginpanel.html
Instead of displaying the long job description in the tooltip for every job listed in the main jobs list, instead add it as the title text for the job name in the job details panel. This avoids bloating the DOM with thousands of longer strings.
We no longer check for the placeholder string "fill me", but I don't think this matters, since we shouldn't be using that string in my opinion anyway (vs leaving it blank) and to me it's more consistent to always show a tooltip, rather than have the user wonder where it has gone.
=> Bug 1153834 - Move job description tooltips to job details panel

webapp/app/js/controllers/jobs.js, webapp/app/js/values.js, webapp/test/unit/controllers/jobs.tests.js
Since more people are likely to want to view mozilla-inbound than mozilla-central. In the future we'll likely replace the homepage with a profile/overview page of some sorts, but for now this seems preferable.
=> Bug 1153361 - Change the default repo to mozilla-inbound

webapp/app/css/treeherder.css, webapp/app/plugins/pluginpanel.html
This tweak fixes Bugzilla bug [1154378](https://bugzilla.mozilla.org/show_bug.cgi?id=1154378).
So, back during work in PR https://github.com/mozilla/treeherder-ui/pull/309 I made the Cancel button in the job details bar a bit less prominent since it is mildly 'destructive', for lack of a better term. James requested it be the same intensity as all the other buttons in the row, so this makes that change.
Here's current:
And here's after:
While I was there I put a hover color on the cancel button, like retrigger's green. I think I recall Ed suggesting that awhile back. I picked a color, but if folks have a particular hue/shade they prefer let me know :) Red over dark is always a bit problematic.
I left the main Cancel All in the resultset bar without that hover color change, for now.
Tested …
=> Bug 1154378 - Make the Cancel btn in job details full opacity

webapp/scripts/web-server.js
Adds a simple 'error' event listener to HttpServer.start. If
error code is "EADDRINUSE", the port is already in use, so prints
a message saying the port is in use, instead of just throwing out
the error.
As discussed in Bugzilla, I've added the necessary changes. I've changed util.puts() to console.log() though, as it's deprecated. If there is any specific reason to keep it at util.puts(), I can just change it back. Changed the color of the error message to red as well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/467)
=> Bug 1141203 - Print a friendly error message when port is already in use when web-server.js is run.

webapp/app/js/providers.js
Ends up escaping characters in DOM ids didn’t work well.  This now
replaces them with hyphens, which DOES work well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/469)
=> Bug 1087349 - replace characters instead of escaping them

webapp/app/plugins/pluginpanel.html
This tweak fixes Bugzilla bug [1154808](https://bugzilla.mozilla.org/show_bug.cgi?id=1154808).
More polish, but I couldn't help myself... making these tips conform to the general convention of leading capital, lower case trailing. I left Talos upper-case, as sort of a proper name.
Current:
Proposed (general, and Talos):
FF Release **37.0.1**
Chrome Latest Release **41.0.2272.118** (64-bit)
Adding @camd for this massive review :)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/471)
=> Bug 1154808 - Case-adjust job panel tab title/tooltips

webapp/app/js/perf.js, webapp/app/perf.html
Replaced http.get call with option collection model service call in perf module
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/468)
=> Bug 1151337-Perfherder graphs should use OptionCollection model

webapp/app/js/services/main.js
If a job (like a build) is not in a group, then the job details string
for filtering by fields showed “unknown ?” as the job-group name and
symbol.  Those are legitimate values internally, but the user shouldn’t
see them.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/473)
=> Bug 1155321 - fix filter params for jobs not in a group

webapp/app/js/controllers/jobs.js, webapp/app/js/models/resultsets_store.js, webapp/app/js/services/pinboard.js
This eliminates persistent (sticky) warnings scoped in Bugzilla bug [1155217](https://bugzilla.mozilla.org/show_bug.cgi?id=1155217).
This is an unrelated part of other assigned work to improve notification UX.
Current:
Proposed:
Our persistence is 4000ms. It is the same for all notifications, however I think I might experiment with passing a duration param to support different persistence (eg. shorter for retrigger). But that is for another bug.
Tested on OSX 10.10.3:
FF Release **37.0.1**
Chrome Latest Release **42.0.2311.90** (64-bit)
Adding @edmorley for review.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/474)
=> Bug 1155217 - Make max-pinboard count notifications not persistent

webapp/app/plugins/controller.js
This is kind of a complex race condition.
By having this code in the main body of ``selectJob``, when switching jobs, if log parsing is complete, then it will call the ``update()`` here, as well as in the ``thTab``.  That's a waste, plus the race condition comes in that the first call to update in the removed ``else`` section of the diff is called in the ``then`` section of a ``$q.all``.
It is possible that, when switching quickly from job X to job Y to job Z, you call the failure summary ajax call on job Y, then on Z, but Z comes back first.  Then when Y comes back, it replaces the data that should be showing for Z.
This change is much safer, because it won't ``update()`` here unless you're waiting on the page for the log parsing to complete.  And the ``selectJobRetryPromise`` is …
=> Bug 1156501 - Failure summary race condition

webapp/app/js/controllers/main.js, webapp/app/js/directives/main.js
This fixes Bugzilla bug [1156820](https://bugzilla.mozilla.org/show_bug.cgi?id=1156820).
This removes the now unused select-on-click directive, from this morning's removal of its behavior in the Filter input, in bug [1156758](https://bugzilla.mozilla.org/show_bug.cgi?id=1156758). It also fixes the 'f' Filter shortcut which broke during that change.
So now when you issue a 'f' shortcut with a pre-existing filter value, we get this:
And the user will now be expected to system cmd/ctrl-a to select that string (or manually drag-select it), to subsequently clear it.
I've done a solid whack of integration testing, manual interaction, clearing, click, filter shortcut invocations, shortcut clears (using the system cmd/ctrl-a to select and clear), and invocations of other shortcuts in the filter …
=> Bug 1156820 - Fix filter shortcut and remove select directive

webapp/app/css/treeherder.css, webapp/app/js/services/main.js, webapp/app/plugins/controller.js
This work fixes Bugzilla bug [1148664](https://bugzilla.mozilla.org/show_bug.cgi?id=1148664).
This prevents the UX problem of sequential notifications from tiling down the page and blocking the jobs and job panel. Specifically we now:
* enforce a maximum number of notifications (proposing 5)
* relocate them to the left side over the revision table so we don't obscure jobs
* expire/prune 'old' non-sticky notifications when new ones arrive
* reduce the height of all notifications
* align the 'X" close icon for sticky notifications to the text baseline
* use a new yellow 'warning' notification if the user retriggers before the job is loaded
* inject the job type (eg. 'B', 'Cpp') into retrigger success messages since the notifications cascade
* make the thModelErrors catch notification …
=> Bug 1148664 - Expire non-sticky notifications with a max queue

webapp/app/js/services/main.js
Fixes [Bug 1157426](https://bugzilla.mozilla.org/show_bug.cgi?id=1157426)
A trivial fix to make things better for the Sheriffs.
This just joins the group symbol with the job symbol so that they are
looked at together.  This makes sure we don’t find a symbol like “8”
that’s also within a SHA.  So string filtering becomes much more
precise.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/484)
=> Bug 1157426 - string filtering more precise

webapp/app/css/treeherder.css, webapp/app/partials/main/jobs.html, webapp/app/plugins/pluginpanel.html
This tweak fixes Bugzilla bug [1155319](https://bugzilla.mozilla.org/show_bug.cgi?id=1155319).
In it we integrate **Job:** and **Filter:** into a single line in the job details panel to save space. Since over time the job details content continues to increase in size.
Here's current production:
Here's proposed:
Here's the proposed link titles. Revised slightly to be consistent with each other, but hopefully still clear about their differences.
Everything seems fine on both browsers.
Tested on OSX 10.10.3:
FF Release **37.0.2**
Chrome Latest Release 42.0.2311.90 (64-bit)
Adding @camd for review and @KWierso for visibility.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/487)
=> Bug 1155319 - Integrate signature into Job field to save space

webapp/app/plugins/controller.js
This fixes Bugzilla bug [1057260](https://bugzilla.mozilla.org/show_bug.cgi?id=1057260).
Per the bug request, this provides the full job name, in the retrigger success notification.
Here's current production:
Here's proposed:
The implication of this change is at narrow browser widths, retrigger notifications may end up again partly obscuring parts of the job table.
Everything seems to print fine on both browsers, as one would expect. 
Tested on OSX 10.10.3:
FF Release **37.0.2**
Chrome Latest Release **42.0.2311.90** (64-bit)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/496)
=> Bug 1057260 - Display full Job name in retrigger notification

webapp/app/js/compareperf.js, webapp/app/js/graphs.js, webapp/app/js/models/resultset.js, webapp/test/mock/resultset_list.json, webapp/test/unit/controllers/jobs.tests.js, webapp/test/unit/models/resultsets.tests.js
Since it's not even checked by the API.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/497)
=> Bug 1159664 - Remove superfluous format param from resultset API calls

webapp/app/js/compareperf.js, webapp/app/js/perf.js, webapp/app/js/perfapp.js, webapp/app/partials/perf/comparectrl.html, webapp/app/partials/perf/comparesubtestctrl.html
Show PGO data, after IRC discussion with avih, pgo will be shown by default with no option to ignore it.  This will not be seen on a try vs. try, but try vs. m-c will show pgo data for m-c and N/A for try.
For tests that have no data on original or new revisions, we will remove those header rows and print a list at the top of the page for tests with no data, otherwise all data will be shown below.
In addition, there are basic error messages printed out for invalid branches or revisions!  It is basic, not fancy, but it at least doesn't leave the user scratching their head.
Lastly the window.document.title is update for compare and subtest compare!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/5 …
=> Bug 1142680 - Write a compare-talos equivalent, items 5,6,9

webapp/app/css/treeherder.css, webapp/app/partials/main/thNotificationsBox.html
This work fixes Bugzilla bug [1159719](https://bugzilla.mozilla.org/show_bug.cgi?id=1159719).
This adds severity-state icons to our notifications. For users who are color-impaired it will help, and I think in quick recognition in general.
I haven't included 'real' notifications in the screen grabs below, I just modified retrigger to be momentarily sticky, and changed its severity for the purposes of reviewing all four types:
Error aka. danger:
Warning:
Info:
Success:
I had also done a version using `ng-class` but the markup wasn't as elegant, or as easy to grok. So I went with `ng-switch` since there isn't any more replicated code than with ng-class. I targeted the new span with a pseudo selector for a fixed width, to avoid replicating it in the -switch markup.
I went with 22px width for …
=> Bug 1159719 - Add severity-state icons to notifications

webapp/app/css/treeherder.css
Prevents unnecessary reflows
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/515)
=> Bug 1162725 - Use flex: 1 with treeherder content

webapp/app/css/treeherder.css, webapp/app/plugins/controller.js, webapp/app/plugins/failure_summary/main.html, webapp/app/plugins/job_details/main.html, webapp/app/plugins/pluginpanel.html, webapp/app/plugins/similar_jobs/main.html, webapp/app/plugins/tabs.js
This work fixes Bugzilla bug [1158901](https://bugzilla.mozilla.org/show_bug.cgi?id=1158901).
This makes the previously off-screen job detail content more discoverable by giving it its own "Job details" tab. We originally mused about 'Extra info' as the title, but I went with the former.
So we can now refer to two pieces of UI, "the job details pane" (where common/universal job data exists) and "the job details tab" (where more unique job data exists).
Notable changes are:
* relocating Buildername to the Job details tab (signed off by @KWierso and other sheriffs)
* providing a dyanmic Job details count, for discoverability if you aren't on that tab
* adding a divider between the two pieces of UI for all tabs
Here's before (resized to display what would otherwise be clipped off screen): …
=> Bug 1158901 - Make off-screen job details discoverable with a tab

webapp/app/css/perf.css, webapp/app/css/treeherder.css, webapp/app/partials/main/thGlobalTopNavPanel.html, webapp/app/perf.html
This work fixes Bugzilla bug [1162706](https://bugzilla.mozilla.org/show_bug.cgi?id=1162706).
This converts our inert Treeherder and Perfherder 'logos' into equivalent nav menus, so you can switch back and forth between platforms, and discover Perfherder from Treeherder.
Here's current (inert logo):
Here's Treeherder proposed (menu posted):
We consciously use the same style as our other right hand nav bar buttons, to cue the user it is navigable, and for consistency. I don't see a downside to that approach.
Here's the proposed tooltip for both:
Here's Perfherder proposed (menu posted):
The only workflow I discovered that doesn't work as expected, is if you use the Perfherder menu to navigate to Treeherder, and then hit 'back' on your browser, we just reload Treeherder instead of reloading …
=> Bug 1162706 - Add UI access between treeherder and perfherder

webapp/app/css/logviewer.css
* Use flexbox for layout, which ensures that scrollbars are always inside
viewport
* Wrap lines instead of providing horizontal scrollbars
* Trim extraneous whitespace off end of log lines before displaying
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/518)
=>  	Bug 1163083 - Improve scrolling behaviour inside log viewer

webapp/app/perf.html
This tweak fixes Bugzilla bug [1164092](https://bugzilla.mozilla.org/show_bug.cgi?id=1164092).
Nothing gripping, the change just quiets this console diagnostic below, when loading Perfherder on Release and Nightly, at least during local development. Chrome is unaffected.
Tested on OSX 10.10.3:
FF Release **37.0.2**
FF Nightly **40.0a1**
Chrome Latest Release **42.0.2311.135** (64-bit)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/521)
=> Bug 1164092 - Add utf-8 encoding to Perfherder to quiet the console

webapp/app/js/config/sample.local.conf.js
Supplemental for Bugzilla bug [1164023](https://bugzilla.mozilla.org/show_bug.cgi?id=1164023).
We've retired treeherder-dev, so also removing it's reference as a backend service from our config file.
Adding @edmorley for review.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/527)
=> Bug 1164023 - Remove treeherder-dev from service config

webapp/app/perf.html
This (hopefully) fixes Bugzilla bug [1164209](https://bugzilla.mozilla.org/show_bug.cgi?id=1164209).
Basically we adjust the href on Perfherder side, so when we switch back to Treeherder we don't touch an empty `/#` fragment and instead just start at `/`. This still works fine with vagrant for local development.
I can mimic the problem and the fix on stage, simulating our new UI navigation menus by:
(problem)
* loading https://treeherder.allizom.org/perf.html#/graphs
* editing the url bar to **treeherder.allizom.org/#** (and enter)
* ...we see a double flash page load
(fix)
* loading https://treeherder.allizom.org/perf.html#/graphs
* editing the url bar to **treeherder.allizom.org/** (and enter)
Given vagrant masks the problem for local development, I can't really prove it's working until …
=> Bug 1164209 - Fix page flash when UI switching from Perf to Treeherder

.gitignore, webapp/scripts/watchr.rb
The directory is empty apart from a .gitkeep, since it only exists to house jstd.log, which is output by watchr.rb. I was going to move the directory around in bug 1056877, but let's just delete it and move the
log file one directory higher up.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/530)
=> Bug 1165702 - Remove webapp/logs/.gitkeep

webapp/app/plugins/controller.js, webapp/app/plugins/pluginpanel.html, webapp/app/plugins/tabs.js
This fixes Bugzilla bug [1166028](https://bugzilla.mozilla.org/show_bug.cgi?id=1166028).
This re-orders the new Job Details tab to be first in the tab sequence in the details panel. We preserve existing rules for Talos display.
Talos pass (unchanged, defaults to Talos tab):
Talos failure (unchanged, defaults to Failure summary):
We add new rule for all other jobs: *any other* job status type other than success lands us on the Failure Summary tab. A successful job now defaults us on the Job Details tab, since there is no 'Failure summary' failure, log parsing status, or raw log availability message to view.
All other jobs, success (changed, defaults to Job details):
All other jobs, eg. failure (unchanged, defaults to Failure summary);
All other jobs, eg. pending/running (unchanged, …
=> Bug 1166028 - Move Job Details tab to be first in the tab sequence

webapp/app/js/perf.js, webapp/app/partials/perf/comparectrl.html, webapp/app/partials/perf/comparesubtestctrl.html
The confidence level is used for deciding which changes to highlight (red/green)
and also for display at the table view.
New behavior:
- Ignore differences below 1.5% and low (<0.5) t-test values.
- Diff above 1.5%, and t-value below 1.0 -> not-sure-regression.
- Above t-value of 1.0 -> confident -> highlight red/green.
- Added the t-test value as the last column at the table ("Conf.")
- Added the actual runs values at the "Runs" tooltip.
TODO:
- Fine tune the t-test constants 0.5 and 1.0 if required.
- Possibly unify this calculation with our regression alerts thresholds.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/532)
=> Bug 1160613 - Use t-test as confidence level for highlight and display
