webapp/app/help.html
Created using search and replace and the list of mappings in buildbot.py
=> Bug 1093650 - Update the list of builds and tests on the help page

webapp/app/js/models/resultsets.js, webapp/app/js/services/resultsets.js
This fixes bug 1090531 as well as bug Bug 1071002
The code for polling was inaccurate in several ways.  
* The polling wasn't using the params on the address bar at all.  So I added that.  
* And in some cases, it wasn't doing the polling when it should (it should still poll with ``startdate`` and ``fromchange`` set).
=> Bug 1090531 - fix refresh on "push not processed yet" page

webapp/app/plugins/talos/main.html
Sorry, I missed this. All the other links open in new windows, this one should too.
=> Add target="_blank" to the cleopatra links.

webapp/app/css/treeherder.css
I think the plain purple is less terrible than what's on there currently.
=> Bug 1125126 - Make the visited link color less hideous

webapp/app/js/directives/main.js, webapp/app/plugins/controller.js, webapp/app/plugins/pluginpanel.html
This had a delay in it due to not triggering the digest.  And the code
was overly heavyweight with a directive.  This is much lighter and
faster.
=> Bug 1097090 - Fix filter by buildername

webapp/app/js/controllers/logviewer.js, webapp/app/js/models/exclusion_profile.js, webapp/app/js/models/job_exclusion.js
minor, but muddies the console on prod and a minor waste of time.
=> Bug 1130544 - change .log to .debug where apropriate

webapp/app/js/models/resultsets_store.js
The job poller was using a timestamp generated on the client to retrieve the updates.
Under some circumstances (eg a significant db replication lag) the
client was missing some updates.
Now it's using the latest last_modified fetched.
If for some reason we miss an update we re-run the same request on the next iteration
=> Bug 1131133 - fix regression on job updates

webapp/app/help.html, webapp/test/mock/job_groups.json
Is this what I'm supposed to do? I force-pushed an amended commit, then made a new PR with it.
=> Bug 1136309 - Document the new spidermonkey builds

webapp/app/plugins/annotations/controller.js
after deleting classification , it's failure classification id is changed to 1 , which makes it unclassified error
=> Bug 1113396 - Make unclassified jobs visible in only-unclassified mode

webapp/app/js/controllers/main.js, webapp/app/js/models/resultsets_store.js, webapp/app/js/services/jobfilters.js, webapp/app/partials/main/thWatchedRepoNavPanel.html
``Tier-2`` jobs are represented in a group by that name in the UI:
=> Bug 1113322 - tier 2 jobs visual representation

webapp/app/js/services/pinboard.js, webapp/app/plugins/pinboard.js
This fixes Bug 1150938
The objective is to capitalize all thNotify.send() messages which began with lower case.
There are a total 7 changes to my knowledge in two files. The changes have been tested by me and my mentor jfrench .It works fine...for any further queries about this bug email me at tapesh.mandal@gmail.com.
Test environment:
OS: Ubuntu 14.04  64 bit
Browser:Mozilla Firefox 33.0 for Ubuntu canonical 1.0
adding @wlach  for review
Regards
Tapesh Mandal
=> Bug 1150938 - Capitalize all thNotify.send() messages

webapp/app/js/controllers/main.js, webapp/app/js/directives/clonejobs.js, webapp/app/js/providers.js, webapp/app/plugins/controller.js
Also stop updates if no job is de-selected (details panel closed)
=> Bug 1095745 - refresh failure summary when all logs parsed

webapp/app/partials/main/thActionButton.html
This just changes the name used in the menu. Part 2 will follow once we get bugherder.mozilla.org set up.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/463)
=> Bug 1154029 - Update mcMerge string in Treeherder to "bugherder" (part 1)

Gruntfile.js, webapp/app/js/logviewer.js, webapp/app/logviewer.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/476)
=>  	Bug 1155330 - Rename some logviewer stuff to keep Grunt happy

webapp/app/partials/main/thWatchedRepoNavPanel.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/481)
=> Bug 1156758 - Don't select all text when selecting the filter field

webapp/app/js/treeherder_app.js, webapp/test/unit/controllers/jobs.tests.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/489)
=> Batch digest updates when http requests return

webapp/app/js/compareperf.js, webapp/app/js/graphs.js, webapp/app/js/models/resultset.js, webapp/app/js/models/resultsets_store.js, webapp/app/plugins/similar_jobs/controller.js, webapp/test/mock/resultset_list.json, webapp/test/unit/controllers/jobs.tests.js, webapp/test/unit/models/resultsets.tests.js
Since it was removed in bug 1097090 & so no longer does anything.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/494)
=> Bug 1139941 - Remove references to obsolete with_jobs URL parameter

webapp/app/css/perf.css, webapp/app/js/compareperf.js, webapp/app/js/perf.js, webapp/app/partials/perf/comparectrl.html, webapp/app/partials/perf/comparesubtestctrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/495)
=> Bug 1142680 - Write a compare-talos equivalent - items 1,2,7,8

webapp/app/js/graphs.js, webapp/app/partials/perf/perfctrl.html
Now if you click on the tooltip for the graph, it'll give you an option to open the subtest view in a new window.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/498)
=> Bug 1142680 - Integrate graphs with compare subtests view

webapp/app/css/perf.css, webapp/app/partials/perf/perfctrl.html
This depends on a commit which has not been merged, which is unintentionally included in the pull request. Just focus on the latest one. :)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/499)
=> Bug 1148067 - Allow getting pushlog when examining graph datapoint

webapp/app/index.html, webapp/app/js/directives/resultsets.js, webapp/app/js/directives/top_nav_bar.js, webapp/app/js/models/repository.js, webapp/app/partials/main/jobs.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/504)
=>  	Bug 1134842 - Link to github revision/pushlog info correctly

webapp/app/js/controllers/sheriff.js, webapp/app/js/graphs.js, webapp/app/js/models/option_collection.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/502)
=>  	Bug 1160621 - Provide a better method for getting option collection map

webapp/app/css/perf.css, webapp/app/js/compareperf.js, webapp/app/js/perf.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/506)
=> Bug 1161264 - when clicking a compare view of an individual subtest we fail

webapp/app/js/compareperf.js, webapp/app/js/graphs.js, webapp/app/js/models/resultset.js, webapp/app/perf.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/509)
=> Bug 1161629 - Use result sets model in perfherder

webapp/app/partials/perf/comparesubtestctrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/511)
=>  	Bug 1162167 - Dancing cat now has kittens in subtest compare view

webapp/app/css/perf.css, webapp/app/js/compareperf.js, webapp/app/js/graphs.js, webapp/app/js/models/resultset.js, webapp/app/js/perfapp.js, webapp/app/partials/perf/graphsctrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/510)
=>  	Bug 1153296 - Add ability to link to two revisions in graphs view

webapp/app/js/models/repository.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/514)
=>  	Bug 1162582 - Fix loading additional results

webapp/app/js/models/repository.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/517)
=> Bug 1163022 - Fix pushloghtml URL generation

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/526)
=> Bug 1164023 - Remove references to the decommissioned treeherder-dev

.gitignore, webapp/.gitignore
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/531)
=> Bug 1165709 - Combine webapp/.gitignore with the top level .gitignore

README.md, docs/installation.rst, webapp/scripts/web-server.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-ui/533)
=> Bug 1165925 - web-server.js should serve index.html at the site root
